In [1]:
# import library
import pandas as pd
import numpy as np

import seaborn as sns 

# Q1. Pandas Version
What's the version of Pandas that you installed?

In [2]:
pd_version = pd.__version__

# answer the question No.1
print(f'The installed Pandas version is {pd_version}')

The installed Pandas version is 2.3.2


## Get the data

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv 

--2025-09-29 19:44:34--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv.1’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.006s  

2025-09-29 19:44:34 (132 MB/s) - ‘car_fuel_efficiency.csv.1’ saved [874188/874188]



In [4]:
# read the csv file
df = pd.read_csv('../Intro/car_fuel_efficiency.csv')

# shows the all records file
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

# Q2. Records count
How many records are in the dataset?

In [5]:
# define records to the variable
records = df.shape[0]

# answer the qustion no.2
print(f'Dataset has {records} records')

Dataset has 9704 records


# Q3. Fuel types
How many fuel types are represented in the dataset?

In [6]:
# total unique value on dataset
distinct_value_of_all_col = df.nunique()
print('Total unique value on dataset :')
print(distinct_value_of_all_col)

print()

# list all values on fuel_type column
fuel_type_values= df['fuel_type'].value_counts()
print('List all the values on fuel type column :')
print(fuel_type_values)

Total unique value on dataset :
engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

List all the values on fuel type column :
fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64


In [7]:
# define the total and unique values on fuel type column
total_unique_of_fuel_type = df['fuel_type'].nunique()
unique_values_of_fuel_type = df['fuel_type'].unique()

# define first and second values
value_1 = unique_values_of_fuel_type[0]
value_2 = unique_values_of_fuel_type[1]

# answer the quesion no.3
print(f'Fuel type has {total_unique_of_fuel_type}, such as {value_1} and {value_2}.')

Fuel type has 2, such as Gasoline and Diesel.


# Q4. Missing values
How many columns in dataset have missing values?

In [8]:
# check missing values
missing_values_check = df.isnull().sum()
missing_values_check

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [9]:
# define missing values columns
missing_values_col = missing_values_check[missing_values_check > 0]
missing_values_col

# define total of missing values
total_missing_values = missing_values_col.count()

# define column names contains missing values
missing_values_name = missing_values_col.index
col_names_1 = missing_values_name[0]
col_names_2 = missing_values_name[1]
col_names_3 = missing_values_name[2]
col_names_4 = missing_values_name[3]

# answer the question no.4
print(f'Amount of missing values in dataset is {total_missing_values}, there are {col_names_1}, {col_names_2}, {col_names_3}, and {col_names_4} columns.')

Amount of missing values in dataset is 4, there are num_cylinders, horsepower, acceleration, and num_doors columns.


# Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia ?

In [10]:
# filter data with origin is Asia
df_asia = df[df['origin'] == 'Asia']
df_asia

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [11]:
# filter the fuel efficiency mpg in Asia
max_fuel_asia = df_asia['fuel_efficiency_mpg'].max()

# truncate the value
value = int(max_fuel_asia * 100) / 100

# answer the question no 5
print(f'Max fuel efficiency cars from Asia is {value:.2f}')

Max fuel efficiency cars from Asia is 23.75


# Q6. Median value of horsepower
- Has it changed?

1. Find the median value of `horsepower` column in dataset.

In [12]:
# show the median of horsepower column
median_horsepower = df['horsepower'].median()
median_horsepower = int(median_horsepower)

print(f'The median value of horsepower before calculate is {median_horsepower}.')

The median value of horsepower before calculate is 149.


2. Next, calculate the most frequent value of same column `horsepower` column.

In [13]:
# the most frequent value in horsepower column
most_frequent_value = df['horsepower'].mode()[0]
most_frequent_value = int(most_frequent_value)

print(f'The most frequent value in horsepower column is {most_frequent_value}.')

The most frequent value in horsepower column is 152.


3. Use `fillna` method to fill the missing values in `horsepower` column with the most frequent value from the previous step.

In [14]:
# handled the missing value with most frequent value in horsepower column
horsepower_clean = df[['horsepower']].fillna(most_frequent_value)
horsepower_clean

horsepower
0          159.0
1           97.0
2           78.0
3          152.0
4          140.0
...          ...
9699       164.0
9700       154.0
9701       138.0
9702       177.0
9703       140.0

[9704 rows x 1 columns]

In [15]:
# check missing values in horsepower column
horsepower_clean.isnull().sum()

horsepower    0
dtype: int64

4. Now, calculate the median value of `horsepower` oncae again.

In [16]:
# show the median of horsepower after using fillna method
new_median = horsepower_clean['horsepower'].median()

# answer the question no.6.
print(f'After handled the missing values in horse powe, the median value has changed. From 149 to 152.')
print('The answer of Question no.6 is "Yes, it increased".')

After handled the missing values in horse powe, the median value has changed. From 149 to 152.
The answer of Question no.6 is "Yes, it increased".


# Q7. Sum of weights

1. Select all the cars from Asia.
2. Select only columns `vehicle_weight` and `model_year`.
3. Select the first 7 values.
4. Get the underlying Numpy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result is `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result is `w`.
9. What's the sum of all the elements of the results? 

- Step by step for question no.7

In [17]:
# select all the cars from Asia
cars_from_asia = df[df['origin'] == 'Asia']
cars_from_asia

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [18]:
# select vehicle_weight and model year columns
selected_col = cars_from_asia[['vehicle_weight', 'model_year']]
selected_col

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [19]:
# select the first 7 values
selected_values = selected_col.head(7).reset_index(drop=True)
selected_values

vehicle_weight  model_year
0     2714.219310        2016
1     2783.868974        2010
2     3582.687368        2007
3     2231.808142        2011
4     2659.431451        2016
5     2844.227534        2014
6     3761.994038        2019

In [20]:
# define a X variable from the values 
X = selected_values.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [21]:
# transpose of X
X_T = X.T
X_T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [22]:
# vector-vector multiplication function
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result
 
# matrix-vector multiplication function 
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result
  
# matrix-matrix multiplication function
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [23]:
# define XTX 
XTX = matrix_matrix_multiplication(X, X_T)
XTX

array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
        10111792.75336224, 11282536.19632532, 11780081.29349753,
        14281180.86123177],
       [11608190.92541486, 11790026.46575708, 14007802.20739725,
        10255171.44187306, 11455668.70489329, 11966096.78727446,
        14531088.48421337],
       [13770311.23387465, 14007802.20739725, 16863697.77478558,
        12031947.83608462, 13574023.463935  , 14232076.05656009,
        17530181.51805091],
       [10111792.75336224, 10255171.44187306, 12031947.83608462,
         9025088.58092514,  9989516.7638366 , 10397924.16669749,
        12456257.9230991 ],
       [11282536.19632532, 11455668.70489329, 13574023.463935  ,
         9989516.7638366 , 11136831.64128077, 11624252.15672766,
        14075069.26273247],
       [11780081.29349753, 11966096.78727446, 14232076.05656009,
        10397924.16669749, 11624252.15672766, 12145826.2645139 ,
        14766233.02574041],
       [14281180.86123177, 14531088.48421337, 175301

In [24]:
# invert of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 3.19409743e+08, -3.45971801e+07, -2.78324217e+08,
        -7.78241981e+07,  1.67379982e+07, -1.72136419e+08,
         2.24690639e+08],
       [ 2.57200169e+08,  8.20389195e+08, -1.13765246e+08,
        -1.69634178e+08, -4.41130505e+08, -3.27953379e+08,
        -2.38828329e+07],
       [-3.90723642e+08, -2.16060684e+08,  1.34235309e+08,
         3.24009117e+08,  7.45998855e+07,  2.31725421e+07,
         5.14736846e+07],
       [-3.31264254e+08, -2.14510114e+08,  3.86914074e+08,
         2.84922793e+08,  1.32418220e+08, -9.49560850e+07,
        -1.61582860e+08],
       [ 1.80453141e+08, -2.20054218e+08, -1.83259500e+08,
        -3.00070277e+07, -2.40526282e+08,  3.98003878e+08,
         9.40973588e+07],
       [-2.36464343e+08, -1.67629002e+08, -7.57998715e+06,
        -2.26195328e+08,  5.04299633e+08,  2.18313030e+08,
        -8.54939349e+07],
       [ 1.99057968e+08,  3.31913714e+07,  6.28987345e+07,
        -1.03693014e+08, -4.64809203e+07, -4.52677339e+07,
        -9.9480870

In [25]:
# create variable of y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [26]:
# shows the shape of various data
X_shape = X.shape
X_T_shape = X_T.shape
XTX_shape = XTX.shape
XTX_inv_shape = XTX_inv.shape

print('Shape of X', X_shape)
print('Shape of X_T', X_T_shape)
print('Shape of XTX', XTX.shape)
print('Shape of XTX_inv', XTX_inv_shape)

Shape of X (7, 2)
Shape of X_T (2, 7)
Shape of XTX (7, 7)
Shape of XTX_inv (7, 7)


In [27]:
# define first formula and w
formula_1 = matrix_matrix_multiplication(X_T, XTX_inv)
w = matrix_vector_multiplication(formula_1, y)

# show the w
w

array([0.21362305, 0.29830933])

In [28]:
# total value in w variable
result = w[0] + w[1]
result = int(result * 100) / 100

# answer the question no.7
print(f'The sum of all the elements of the result is {result}')

The sum of all the elements of the result is 0.51
